//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captura.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Captura.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on Top 的本地化字符串。
        /// </summary>
        public static string AlwaysOnTop {
            get {
                return ResourceManager.GetString("AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Captura 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio 的本地化字符串。
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Saved 的本地化字符串。
        /// </summary>
        public static string AudioSaved {
            get {
                return ResourceManager.GetString("AudioSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back Color 的本地化字符串。
        /// </summary>
        public static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border Color 的本地化字符串。
        /// </summary>
        public static string BorderColor {
            get {
                return ResourceManager.GetString("BorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border Thickness 的本地化字符串。
        /// </summary>
        public static string BorderThickness {
            get {
                return ResourceManager.GetString("BorderThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom 的本地化字符串。
        /// </summary>
        public static string Bottom {
            get {
                return ResourceManager.GetString("Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Capture Duration (in seconds) 的本地化字符串。
        /// </summary>
        public static string CaptureDuration {
            get {
                return ResourceManager.GetString("CaptureDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changelog 的本地化字符串。
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Recent List 的本地化字符串。
        /// </summary>
        public static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color 的本地化字符串。
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Exit 的本地化字符串。
        /// </summary>
        public static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Output file path to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyOutPathClipboard {
            get {
                return ResourceManager.GetString("CopyOutPathClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Path 的本地化字符串。
        /// </summary>
        public static string CopyPath {
            get {
                return ResourceManager.GetString("CopyPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy to Clipboard 的本地化字符串。
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CornerRadius 的本地化字符串。
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize Click and Keystrokes Overlays 的本地化字符串。
        /// </summary>
        public static string CustomizeClickAndKeysOverlays {
            get {
                return ResourceManager.GetString("CustomizeClickAndKeysOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay cannot be greater than Duration 的本地化字符串。
        /// </summary>
        public static string DelayGtDuration {
            get {
                return ResourceManager.GetString("DelayGtDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk 的本地化字符串。
        /// </summary>
        public static string Disk {
            get {
                return ResourceManager.GetString("Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Donate 的本地化字符串。
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Error Occured 的本地化字符串。
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extras 的本地化字符串。
        /// </summary>
        public static string Extras {
            get {
                return ResourceManager.GetString("Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFMpeg Folder 的本地化字符串。
        /// </summary>
        public static string FFMpegFolder {
            get {
                return ResourceManager.GetString("FFMpegFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFMpeg Log 的本地化字符串。
        /// </summary>
        public static string FFMpegLog {
            get {
                return ResourceManager.GetString("FFMpegLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Horizontal 的本地化字符串。
        /// </summary>
        public static string FlipX {
            get {
                return ResourceManager.GetString("FlipX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flip Vertical 的本地化字符串。
        /// </summary>
        public static string FlipY {
            get {
                return ResourceManager.GetString("FlipY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FontSize 的本地化字符串。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frame Rate 的本地化字符串。
        /// </summary>
        public static string FrameRate {
            get {
                return ResourceManager.GetString("FrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Screen 的本地化字符串。
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gif 的本地化字符串。
        /// </summary>
        public static string Gif {
            get {
                return ResourceManager.GetString("Gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide on Full Screen ScreenShot 的本地化字符串。
        /// </summary>
        public static string HideOnFullScreenShot {
            get {
                return ResourceManager.GetString("HideOnFullScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 的本地化字符串。
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys 的本地化字符串。
        /// </summary>
        public static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Saved. Image taken was Empty 的本地化字符串。
        /// </summary>
        public static string ImgEmpty {
            get {
                return ResourceManager.GetString("ImgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Format 的本地化字符串。
        /// </summary>
        public static string ImgFormat {
            get {
                return ResourceManager.GetString("ImgFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Saved to Clipboard 的本地化字符串。
        /// </summary>
        public static string ImgSavedClipboard {
            get {
                return ResourceManager.GetString("ImgSavedClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Saved to Disk 的本地化字符串。
        /// </summary>
        public static string ImgSavedDisk {
            get {
                return ResourceManager.GetString("ImgSavedDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imgur 的本地化字符串。
        /// </summary>
        public static string Imgur {
            get {
                return ResourceManager.GetString("Imgur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imgur Upload Failed 的本地化字符串。
        /// </summary>
        public static string ImgurFailed {
            get {
                return ResourceManager.GetString("ImgurFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imgur Upload Successful 的本地化字符串。
        /// </summary>
        public static string ImgurSuccess {
            get {
                return ResourceManager.GetString("ImgurSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading to Imgur 的本地化字符串。
        /// </summary>
        public static string ImgurUploading {
            get {
                return ResourceManager.GetString("ImgurUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Mouse Clicks 的本地化字符串。
        /// </summary>
        public static string IncludeClicks {
            get {
                return ResourceManager.GetString("IncludeClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Cursor 的本地化字符串。
        /// </summary>
        public static string IncludeCursor {
            get {
                return ResourceManager.GetString("IncludeCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include KeyStrokes 的本地化字符串。
        /// </summary>
        public static string IncludeKeys {
            get {
                return ResourceManager.GetString("IncludeKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keystrokes 的本地化字符串。
        /// </summary>
        public static string Keystrokes {
            get {
                return ResourceManager.GetString("Keystrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string Left {
            get {
                return ResourceManager.GetString("Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speaker Output Source 的本地化字符串。
        /// </summary>
        public static string LoopbackSource {
            get {
                return ResourceManager.GetString("LoopbackSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max items to persist 的本地化字符串。
        /// </summary>
        public static string MaxRecent {
            get {
                return ResourceManager.GetString("MaxRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Text Length 的本地化字符串。
        /// </summary>
        public static string MaxTextLength {
            get {
                return ResourceManager.GetString("MaxTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microphone Source 的本地化字符串。
        /// </summary>
        public static string MicSource {
            get {
                return ResourceManager.GetString("MicSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize on Capture Start 的本地化字符串。
        /// </summary>
        public static string MinCapture {
            get {
                return ResourceManager.GetString("MinCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize to System Tray 的本地化字符串。
        /// </summary>
        public static string MinTray {
            get {
                return ResourceManager.GetString("MinTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Clicks 的本地化字符串。
        /// </summary>
        public static string MouseClicks {
            get {
                return ResourceManager.GetString("MouseClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Saved 的本地化字符串。
        /// </summary>
        public static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only Audio 的本地化字符串。
        /// </summary>
        public static string OnlyAudio {
            get {
                return ResourceManager.GetString("OnlyAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Output Folder 的本地化字符串。
        /// </summary>
        public static string OpenOutFolder {
            get {
                return ResourceManager.GetString("OpenOutFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output Folder 的本地化字符串。
        /// </summary>
        public static string OutFolder {
            get {
                return ResourceManager.GetString("OutFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Padding 的本地化字符串。
        /// </summary>
        public static string PaddingX {
            get {
                return ResourceManager.GetString("PaddingX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Padding 的本地化字符串。
        /// </summary>
        public static string PaddingY {
            get {
                return ResourceManager.GetString("PaddingY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Paused 的本地化字符串。
        /// </summary>
        public static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause | Resume 的本地化字符串。
        /// </summary>
        public static string PauseResume {
            get {
                return ResourceManager.GetString("PauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause/Resume Recording 的本地化字符串。
        /// </summary>
        public static string PauseResumeRecording {
            get {
                return ResourceManager.GetString("PauseResumeRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy 的本地化字符串。
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality 的本地化字符串。
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radius 的本地化字符串。
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording... 的本地化字符串。
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Recording is in progress. Are you sure you want to exit? 的本地化字符串。
        /// </summary>
        public static string recordingExit {
            get {
                return ResourceManager.GetString("recordingExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record | Stop 的本地化字符串。
        /// </summary>
        public static string RecordStop {
            get {
                return ResourceManager.GetString("RecordStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refreshed 的本地化字符串。
        /// </summary>
        public static string Refreshed {
            get {
                return ResourceManager.GetString("Refreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region 的本地化字符串。
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Region Selector 的本地化字符串。
        /// </summary>
        public static string RegionSelector {
            get {
                return ResourceManager.GetString("RegionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove from List 的本地化字符串。
        /// </summary>
        public static string RemoveFromList {
            get {
                return ResourceManager.GetString("RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat 的本地化字符串。
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize 的本地化字符串。
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string Right {
            get {
                return ResourceManager.GetString("Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rotate 的本地化字符串。
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Location 的本地化字符串。
        /// </summary>
        public static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen 的本地化字符串。
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenShot 的本地化字符串。
        /// </summary>
        public static string ScreenShot {
            get {
                return ResourceManager.GetString("ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenShot Active Window 的本地化字符串。
        /// </summary>
        public static string ScreenShotActiveWindow {
            get {
                return ResourceManager.GetString("ScreenShotActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenShot Desktop 的本地化字符串。
        /// </summary>
        public static string ScreenShotDesktop {
            get {
                return ResourceManager.GetString("ScreenShotDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenShot Saved 的本地化字符串。
        /// </summary>
        public static string ScreenShotSaved {
            get {
                return ResourceManager.GetString("ScreenShotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ScreenShot Transforms 的本地化字符串。
        /// </summary>
        public static string ScreenShotTransforms {
            get {
                return ResourceManager.GetString("ScreenShotTransforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select FFMpeg Folder 的本地化字符串。
        /// </summary>
        public static string SelectFFMpegFolder {
            get {
                return ResourceManager.GetString("SelectFFMpegFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Output Folder 的本地化字符串。
        /// </summary>
        public static string SelectOutFolder {
            get {
                return ResourceManager.GetString("SelectOutFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show System Tray Notifications 的本地化字符串。
        /// </summary>
        public static string ShowSysNotify {
            get {
                return ResourceManager.GetString("ShowSysNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Delay (in ms) 的本地化字符串。
        /// </summary>
        public static string StartDelay {
            get {
                return ResourceManager.GetString("StartDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 start param error or null 的本地化字符串。
        /// </summary>
        public static string StartParamError {
            get {
                return ResourceManager.GetString("StartParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start/Stop Recording 的本地化字符串。
        /// </summary>
        public static string StartStopRecording {
            get {
                return ResourceManager.GetString("StartStopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Stopped 的本地化字符串。
        /// </summary>
        public static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Top 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transforms 的本地化字符串。
        /// </summary>
        public static string Transforms {
            get {
                return ResourceManager.GetString("Transforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Proxy 的本地化字符串。
        /// </summary>
        public static string UseProxy {
            get {
                return ResourceManager.GetString("UseProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Proxy Authentication 的本地化字符串。
        /// </summary>
        public static string UseProxyAuth {
            get {
                return ResourceManager.GetString("UseProxyAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 80128d52-bdc8-405e-969a-7c574e2b461b 的本地化字符串。
        /// </summary>
        public static string validateId {
            get {
                return ResourceManager.GetString("validateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 51livetool 的本地化字符串。
        /// </summary>
        public static string validateName {
            get {
                return ResourceManager.GetString("validateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable Frame Rate 的本地化字符串。
        /// </summary>
        public static string VarFrameRate {
            get {
                return ResourceManager.GetString("VarFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video 的本地化字符串。
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Encoder 的本地化字符串。
        /// </summary>
        public static string VideoEncoder {
            get {
                return ResourceManager.GetString("VideoEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Saved 的本地化字符串。
        /// </summary>
        public static string VideoSaved {
            get {
                return ResourceManager.GetString("VideoSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Source 的本地化字符串。
        /// </summary>
        public static string VideoSource {
            get {
                return ResourceManager.GetString("VideoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting... 的本地化字符串。
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Want to Translate? 的本地化字符串。
        /// </summary>
        public static string WantToTranslate {
            get {
                return ResourceManager.GetString("WantToTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebCam 的本地化字符串。
        /// </summary>
        public static string WebCam {
            get {
                return ResourceManager.GetString("WebCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebCam View 的本地化字符串。
        /// </summary>
        public static string WebCamView {
            get {
                return ResourceManager.GetString("WebCamView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window 的本地化字符串。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 560 的本地化字符串。
        /// </summary>
        public static string WindowHeight {
            get {
                return ResourceManager.GetString("WindowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 420 的本地化字符串。
        /// </summary>
        public static string WindowWidth {
            get {
                return ResourceManager.GetString("WindowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
